name: Node.js CI

on:
  push:
    branches: [ main, add-unix-wildcard-and-multiple-platforms ]
  pull_request:
    branches: [ main, add-unix-wildcard-and-multiple-platforms ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
